# Generated by Django 4.2.3 on 2024-01-25 14:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='endDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
