# Generated by Django 4.2.3 on 2024-01-27 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_pledge_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='endDateTime',
            new_name='date_close',
        ),
    ]
